language: android
sudo: false ## Enable container-based infrastructure
android:
  components:
    - build-tools-23.0.0
    - android-23
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_install:
    - chmod +x gradlew
    - chmod +x make
script:
    - ./make