language: android
sudo: false ## Enable container-based infrastructure
android:
  components:
    - build-tools-23.0.1
    - android-23
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_install:
    - chmod +x gradlew
    - chmod +x scripts/do.sh
script:
    - ./scripts/do.sh
    - bash <(curl -s https://codecov.io/bash)
